language: python

python:
  - '3.6'

install:
  - pip install -r requirements.txt

script:
  - python setup.py install
  - make style-check
  - pytest --cov=./mozart tests

after_success:
  - codecov
